{% set name = "snowflake-ml-python" %}
{% set version = "1.54.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/snowflake_ml_python-{{ version }}.tar.gz
  sha256: e9810d71fe091e026e0c3052f152e92049e49f8c2f1cc1126bbc93171a4a4fef
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolatio
  number: 0
requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - anyio >=3.5.0,<5
    - cachetools >=3.1.1
    - cloudpickle >=2.0.0
    - fsspec >=2024.6.1,<2026
    - h2 >=4.3.0,<5
    - importlib_resources >=6.1.1,<7
    - jinja2 >=3.1.0,<4
    - numpy >=1.23,<3
    - packaging >=20.9,<26
    - pandas >=2.1.4,<3
    - platformdirs <5
    - pyarrow
    - pydantic >=2.8.2,<3
    - pyjwt >=2.0.0,<3
    - pytimeparse >=1.1.8,<2
    - pyyaml >=6.0,<7
    - requests
    - retrying >=1.3.3,<2
    - scikit-learn <1.9
    - scipy >=1.9,<2
    - shap >=0.46.0,<1
    - snowflake-connector-python >=3.17.3,<5
    - snowflake-snowpark-python >=1.17.0,<2,!=1.26.0
    - sqlparse >=0.4,<1
    - tqdm <5
    - typing-extensions >=4.1.0,<5
    - xgboost <4
    - python >={{ python_min }},<3.14
  run_constrained:
    - altair >=5,<7
    - catboost >=1.2.0,<2
    - keras >=2.0.0,<4
    - lightgbm >=4.1.0,<5
    - mlflow >=2.16.0,<4
    - prophet >=1.1.0,<2
    - pytorch >=2.0.1,<3
    - sentence-transformers >=2.7.0,<6
    - sentencepiece >=0.1.95,<0.3
    - streamlit >=1.30.0,<2
    - tensorflow >=2.17.0,<3
    - tokenizers >=0.15.1,<1
    - torchdata >=0.4,<1
    - transformers >=4.39.3,!=4.51.3,<6
test:
  imports:
    - snowflake.cortex
    - snowflake.ml
    - snowflake.ml.modeling
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  description: |
    Snowflake ML client Library is used for interacting with Snowflake to build machine learning solutions.
    Functionalities include feature engineering, modeling, model management, deployment, etc
  dev_url: https://github.com/snowflakedb/snowflake-ml-python
  doc_url: https://github.com/snowflakedb/snowflake-ml-python/blob/main/README.md
  home: https://github.com/snowflakedb/snowflake-ml-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake ML Library
extra:
  recipe-maintainers:
    - sfc-gh-sheli
    - sfc-gh-ssardana
    - sfc-gh-clin
    - sfc-gh-valamuri
    - sfc-gh-jdouglas
    - sfc-gh-gren
    - sfc-gh-gmurlidhar
    - sfc-gh-jiehuang
    - sfc-gh-kdickerson
    - sfc-gh-skoduri
    - sfc-gh-schindirala
    - sfc-gh-pramachandran
    - sfc-gh-rsureshbabu
    - sfc-gh-hayu
    - sfc-gh-aponnusamy
    - sfc-gh-thoyt
    - sfc-gh-sdas
    - sfc-gh-wzhao
    - sfc-gh-pdorairaj
    - sfc-gh-srudenko
